import type { AgenticMarketplaceService } from "@/modules/agentic-marketplace/contracts";

const shared = {
  scheme: "exact",
  paymentAsset: "USDC",
  payTo: null,
  maxAmountRequired: null,
  agentReady: true,
  liveTapeMentions: 0,
};

export const fallbackMarketplaceServices: AgenticMarketplaceService[] = [
  {
    id: "fallback-alpha-vantage",
    title: "Alpha Vantage Market Data",
    operationName: "Quote API",
    description:
      "Real-time and historical stock market data for agents and trading workflows.",
    category: "data",
    categoryLabel: "Data",
    network: "base-sepolia",
    networkLabel: "Base Sepolia",
    host: "api-dev.intra-tls2.dctx.link",
    providerName: "Questflow",
    resourceUrl:
      "https://api-dev.intra-tls2.dctx.link/x402/agent/qrn:agent:68dba0e582f61ca4a1686963",
    method: "POST",
    priceLabel: "Up to $0.10",
    searchText: "alpha vantage market data questflow stocks historical quote",
    ...shared,
  },
  {
    id: "fallback-heurist-twitter",
    title: "Elfa Twitter Intelligence Agent",
    operationName: "Search Mentions",
    description:
      "Search influential Twitter mentions for tokens and crypto topics with agent-friendly inputs.",
    category: "social",
    categoryLabel: "Social",
    network: "base",
    networkLabel: "Base",
    host: "mesh.heurist.xyz",
    providerName: "Heurist",
    resourceUrl:
      "https://mesh.heurist.xyz/x402/agents/ElfaTwitterIntelligenceAgent/search_mentions",
    method: "POST",
    priceLabel: "Up to $0.01",
    searchText: "elfa twitter intelligence search mentions heurist social crypto",
    ...shared,
  },
  {
    id: "fallback-firecrawl",
    title: "Firecrawl Extract Web Data",
    operationName: "Extract Web Data",
    description:
      "Extract structured data from one or many webpages with a natural-language prompt.",
    category: "search",
    categoryLabel: "Search",
    network: "base",
    networkLabel: "Base",
    host: "mesh.heurist.xyz",
    providerName: "Heurist",
    resourceUrl:
      "https://mesh.heurist.xyz/x402/agents/FirecrawlSearchDigestAgent/firecrawl_extract_web_data",
    method: "POST",
    priceLabel: "Up to $0.01",
    searchText: "firecrawl extract web data heurist search scrape structured",
    ...shared,
  },
  {
    id: "fallback-minimax",
    title: "MiniMax Media Studio",
    operationName: "Generate Media",
    description:
      "Generate images, videos, and speech from a single x402-enabled multimodal endpoint.",
    category: "media",
    categoryLabel: "Media",
    network: "base",
    networkLabel: "Base",
    host: "api.questflow.ai",
    providerName: "Questflow",
    resourceUrl: "https://api.questflow.ai/x402/swarm/qrn:swarm:68fafe670ebd74a7913a8091",
    method: "POST",
    priceLabel: "Up to $0.50",
    searchText: "minimax media image video speech questflow multimodal",
    ...shared,
  },
  {
    id: "fallback-web3-trader",
    title: "Web3 Trader",
    operationName: "Trading Intelligence",
    description:
      "Token, DeFi pool, trending NFT, and Twitter intelligence packaged into one trading agent.",
    category: "trading",
    categoryLabel: "Trading",
    network: "base",
    networkLabel: "Base",
    host: "api.questflow.ai",
    providerName: "Questflow",
    resourceUrl: "https://api.questflow.ai/x402/swarm/qrn:swarm:68f8d51b0f57b44388f953a1",
    method: "POST",
    priceLabel: "Up to $0.50",
    searchText: "web3 trader defi nft twitter intelligence questflow trading",
    ...shared,
  },
  {
    id: "fallback-browser",
    title: "Browser Automation",
    operationName: "Automate the Web",
    description:
      "Managed browser automation for agents that need secure and scalable web interactions.",
    category: "infrastructure",
    categoryLabel: "Infrastructure",
    network: "base",
    networkLabel: "Base",
    host: "api.questflow.ai",
    providerName: "Questflow",
    resourceUrl: "https://api.questflow.ai/x402/swarm/qrn:swarm:68ec8a8e7938a7458fbd2615",
    method: "POST",
    priceLabel: "Up to $0.50",
    searchText: "browser automation infrastructure questflow managed web interactions",
    ...shared,
  },
];
